const actions = {
  ADD_NEW_DEVICE: 'ADD_NEW_DEVICE',
  ADD_DEVICE_SUCCESS: 'ADD_DEVICE_SUCCESS',
  ADD_DEVICE_FAILURE: 'ADD_DEVICE_FAILURE',

  GET_ALL_DEVICES: 'GET_ALL_DEVICES',
  GET_ALL_DEVICES_SUCCESS: 'GET_ALL_DEVICES_SUCCESS',
  GET_ALL_DEVICES_FAILURE: 'GET_ALL_DEVICES_FAILURE',

  DELETE_DEVICE: 'DELETE_DEVICE',
  DELETE_DEVICE_SUCCESS: 'DELETE_DEVICE_SUCCESS',
  DELETE_DEVICE_FAILURE: 'DELETE_DEVICE_FAILURE'
}

export default actions;
