const actions = {
  GET_ALL_DEVICELOGS: 'GET_ALL_DEVICELOGS',
  GET_ALL_DEVICELOGS_SUCCESS: 'GET_ALL_DEVICELOGS_SUCCESS',
  GET_ALL_DEVICELOGS_FAILURE: 'GET_ALL_DEVICELOGS_FAILURE'
}

export default actions;
